apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gatekeeper-relay.fullname" . }}-config
  labels:
    {{- include "gatekeeper-relay.labels" . | nindent 4 }}
data:
  config.yaml: |
    server: {{ .Values.server | quote }}
    max_consecutive_failures: {{ .Values.maxConsecutiveFailures }}

    channels:
      {{- range .Values.channels }}
      - name: {{ .name | quote }}
        token: ${{ "{" }}{{ .tokenKey }}{{ "}" }}
        destination: {{ .destination | quote }}
        {{- if .workers }}
        workers: {{ .workers }}
        {{- end }}
      {{- end }}
