apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatekeeper-acme-cache
  labels:
    app: gatekeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
