apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper-secrets
  labels:
    app: gatekeeper
type: Opaque
stringData:
  # Avvo secrets
  AVVO_SLACK_SIGNING_SECRET: "replace-with-actual-secret"
  AVVO_GCAL_CHANNEL_TOKEN: "replace-with-actual-token"
  # Nolo secrets
  NOLO_SLACK_SIGNING_SECRET: "replace-with-actual-secret"
  # Martindale secrets
  MARTINDALE_GITHUB_WEBHOOK_SECRET: "replace-with-actual-secret"
