apiVersion: v1
kind: Service
metadata:
  name: gatekeeper
  labels:
    app: gatekeeper
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: gatekeeper
---
apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-metrics
  labels:
    app: gatekeeper
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    app: gatekeeper
