apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatekeeperd.fullname" . }}
  labels:
    {{- include "gatekeeperd.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.tls.enabled }}
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    {{- else }}
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    {{- end }}
  selector:
    {{- include "gatekeeperd.selectorLabels" . | nindent 4 }}
---
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatekeeperd.fullname" . }}-metrics
  labels:
    {{- include "gatekeeperd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "gatekeeperd.selectorLabels" . | nindent 4 }}
{{- end }}
