apiVersion: v2
name: gatekeeper-relay
description: Relay client for gatekeeper that enables webhook delivery to private networks
type: application
version: 0.2.13
appVersion: "0.2.13"
keywords:
  - webhook
  - relay
  - proxy
  - private-network
maintainers:
  - name: Tight Line
    email: certs@example.com
