apiVersion: v2
name: gatekeeperd
description: Webhook authentication proxy server for validating and forwarding webhooks
type: application
version: 0.1.11
appVersion: "0.1.11"
keywords:
  - webhook
  - proxy
  - authentication
  - slack
  - github
  - relay
maintainers:
  - name: Tight Line
    email: certs@example.com
dependencies:
  - name: valkey
    version: "~2.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled,redis.bundled
    alias: valkey
